name: kaolin_test
channels:
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/main
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2023.01.10
  - certifi=2020.6.20
  - ld_impl_linux-64=2.38
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - ncurses=6.4
  - openssl=1.1.1t
  - path=16.2.0
  - python=3.6.13
  - readline=8.2
  - sqlite=3.41.2
  - tk=8.6.12
  - wheel=0.37.1
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
      - absl-py==1.4.0
      - astunparse==1.6.3
      - cached-property==1.5.2
      - cachetools==4.2.4
      - charset-normalizer==2.0.12
      - colorama==0.4.5
      - commonmark==0.9.1
      - cppcuda-tutorial==1.0
      - cycler==0.11.0
      - cython==0.29.20
      - dataclasses==0.8
      - decorator==4.4.2
      - dill==0.3.4
      - future==0.18.3
      - google-auth==2.18.0
      - google-auth-oauthlib==0.4.6
      - googledrivedownloader==0.4
      - grpcio==1.48.2
      - h5py==3.1.0
      - idna==3.4
      - imageio==2.15.0
      - importlib-metadata==4.8.3
      - importlib-resources==5.4.0
      - isodate==0.6.1
      - joblib==1.1.1
      - kiwisolver==1.3.1
      - llvmlite==0.36.0
      - markdown==3.3.7
      - matplotlib==3.3.4
      - miniball==0.2
      - networkx==2.5.1
      - numba==0.53.1
      - numpy==1.19.5
      - numpy-stl==3.0.1
      - oauthlib==3.2.2
      - ocnn==2.2.1
      - opencv-python==4.5.1.48
      - openexr==1.3.9
      - pandas==1.1.5
      - pillow==8.4.0
      - pip==21.3.1
      - plyfile==0.8
      - polyscope==1.3.1
      - protobuf==3.19.6
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pybind11==2.10.4
      - pydevd-pycharm==232.9921.36
      - pyexr==0.3.10
      - pyglet==1.5.1
      - pygments==2.14.0
      - pymesh==1.0.2
      - pyngpmesh==1.0
      - pyparsing==3.0.9
      - pytest-runner==5.3.2
      - python-dateutil==2.8.2
      - python-utils==3.5.2
      - pytz==2023.3
      - pywavelets==1.1.1
      - rdflib==5.0.0
      - requests==2.27.1
      - requests-oauthlib==1.3.1
      - rich==12.6.0
      - rsa==4.9
      - scikit-image==0.17.2
      - scikit-learn==0.24.2
      - scipy==1.5.4
      - setuptools==59.6.0
      - six==1.16.0
      - sourceinspect==0.0.4
      - taichi==1.0.4
      - tensorboard==2.10.1
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - threadpoolctl==3.1.0
      - tifffile==2020.9.3
      - tinyobjloader==0.1
      - torch==1.8.0+cu111
      - torch-cluster==1.5.9
      - torch-geometric==1.4.1
      - torch-scatter==2.0.6
      - torch-sparse==0.6.10
      - torch-spline-conv==1.2.1
      - tqdm==4.64.1
      - trimesh==3.21.6
      - typing-extensions==4.1.1
      - urllib3==1.26.15
      - usd-core==23.5
      - vtk==9.2.6
      - werkzeug==2.0.3
      - zipp==3.6.0
